name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Sonar scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install Sonar scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          $scanner = "${{ runner.temp }}\scanner\dotnet-sonarscanner"

          & $scanner begin /k:"pedrogerhard_rest-with-asp-net-10-gerhard" /o:"pedrogerhard" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1

          if (-not $sln) {
            Write-Error "Nenhum arquivo .sln encontrado."
            exit 1
          }

          dotnet build $sln.FullName --configuration Release

          & $scanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
